### ISSUE TITLE
IllegalStateException: java.io.EOFException

### ISSUE THREAD

**Issue by wotnurwasfrage** [ChanceSD/AncientGates#25]
```
[17:46:40 WARN]: Could not pass incoming plugin message to AncientGates v2.1
java.lang.IllegalStateException: java.io.EOFException
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:385) ~[spigot.jar:git-Spigot-26dfd01-ad2f806]
        at org.mcteam.ancientgates.listeners.PluginMessengerListener.onPluginMessageReceived(PluginMessengerListener.java:49) ~[?:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:427) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:2086) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PacketPlayInCustomPayload.a(SourceFile:55) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PacketPlayInCustomPayload.a(SourceFile:8) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-26dfd01-ad2f806]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.EOFException
        at java.io.DataInputStream.readShort(DataInputStream.java:315) ~[?:1.8.0_171]
        at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:383) ~[spigot.jar:git-Spigot-26dfd01-ad2f806]
        ... 14 more

```-------------------------------------------

how i can fix this? i dont see any bugs, but this WARN dont stops in console… :/

**Comment by ChanceSD** [comment]
I don't know if you're still using the plugin but for anyone else having this issue just disable bungeecord support for now.

**Comment by k-jiang** [comment]
Similar things happened in 1.17:
```
[21:28:47] [Server thread/WARN]: [AncientGates] Plugin AncientGates v2.5 generated an exception whilst handling plugin message
java.lang.IllegalStateException: java.io.EOFException
	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:336) ~[patched_1.17.jar:git-Paper-66]
	at org.mcteam.ancientgates.listeners.PluginMessengerListener.onPluginMessageReceived(PluginMessengerListener.java:49) ~[?:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3080) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:38) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:7) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1340) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1273) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1184) ~[patched_1.17.jar:git-Paper-66]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-66]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readShort(Unknown Source) ~[?:?]
	at com.google.common.io.ByteStreams$ByteArrayDataInputStream.readShort(ByteStreams.java:334) ~[patched_1.17.jar:git-Paper-66]
	... 19 more
```
