### ISSUE TITLE
[1.16.1] Water portal don't work

### ISSUE THREAD

**Issue by splintermik** [ChanceSD/AncientGates#37]
**Describe the bug**

Hello, since I switched to 1.16.1, my water portal doesn't work at all.

the other materials seem to be working.

I have by default the material water

error :

[16:41:52] [Server thread/INFO]: splintermik issued server command: /gate create test
[16:41:52] [Server thread/INFO]: [AncientGates] created new gate test
[16:41:58] [Server thread/INFO]: splintermik issued server command: /gate setfrom test
[16:42:05] [Server thread/INFO]: splintermik issued server command: /gate open test
[16:42:05] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gate' in plugin AncientGates v2.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1912) ~[?:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1723) ~[?:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at org.mcteam.ancientgates.util.BlockUtil.isPortalGateMaterial(BlockUtil.java:89) ~[?:?]
	at org.mcteam.ancientgates.Gates.open(Gates.java:104) ~[?:?]
	at org.mcteam.ancientgates.commands.base.CommandOpen.perform(CommandOpen.java:43) ~[?:?]
	at org.mcteam.ancientgates.commands.BaseCommand.execute(BaseCommand.java:63) ~[?:?]
	at org.mcteam.ancientgates.Plugin.handleCommand(Plugin.java:399) ~[?:?]
	at org.mcteam.ancientgates.Plugin.onCommand(Plugin.java:384) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-131]
	... 18 more
[16:45:16] [Server thread/INFO]: splintermik issued server command: /gate setmaterial test air
[16:45:17] [Server thread/INFO]: splintermik issued server command: /gate open test

**Plugin and Server version**

server version : Paper-131 (MC: 1.16.1

plugin version : AncientGates v2.3

**Comment by ChanceSD** [comment]
Let me know if the new version on spigot fixes this issue.

**Comment by splintermik** [comment]
It's working properly! :) 
thanks
