### ISSUE TITLE
Couldn't enable the plugin on KCauldron 1.7.10

### ISSUE THREAD

**Issue by Polar-Pumpkin** [ChanceSD/AncientGates#39]
**Describe the bug**
throw `java.lang.NoSuchMethodError` when load it on KCauldron 1.7.10

**To Reproduce**
Use KCauldron to setup Minecraft server,

```
[15:01:26 ERROR]: Error occurred while enabling AncientGates v2.4-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: guava10.com.google.common.cache.CacheBuilder.build()Lguava10/com/google/common/cache/Cache;
        at org.mcteam.ancientgates.util.XMaterial.<clinit>(XMaterial.java:1309) ~[?:?]
        at org.mcteam.ancientgates.util.types.GateMaterial.<clinit>(GateMaterial.java:12) ~[?:?]
        at org.mcteam.ancientgates.Conf.<clinit>(Conf.java:40) ~[?:?]
        at org.mcteam.ancientgates.Plugin.onEnable(Plugin.java:153) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Expected behavior**
hum... Plugin load correctly?

**Plugin and Server version**
```
ver AncientGate
[15:07:25 INFO]: AncientGates version 2.4-SNAPSHOT
[15:07:25 INFO]: Easily create portals with any custom design.
[15:07:25 INFO]: Author: NoChanceSD
ver
[15:08:38 INFO]: This server is running KCauldron version 1.7.10-R0.1-SNAPSHOT (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
```

**Screenshots (Optional)**
Sorry, I haven't.

**Additional context (Optional)**
In the previous version, the experience of using KCauldron was not very good, and there were many strange bugs. For example, the material disappeared shortly after switching the portal material, and then the portal also became invalid. Close and reopen have no effect. Only delete and recreate the portal. Especially if use WATER or LAVA portal material, the portal will directly become invalid and cannot teleport any more. Reopen it will prompt `The gate could not open. The from location is not air.`, water and magma will flow around (but looking at your update log this bug seems to have been fixed), so I want to try the new version , But this error occurred.

There is no error log for the problems I mentioned above, and there was no deletion of the portal or other something, and the portal was still recorded in the data file. Use `/gate list` can see all the gates.
I also know that the stability of KCauldron 1.7.10 is very poor, and there are often various strange unexplainable problems. If you can't or don't want to spend too much energy on it, then forget it.

**Comment by ChanceSD** [comment]
Sorry for the lack of response, it has been a long time but I think this was fixed by previous updates. That's a pretty old version and I don't have any testing enviroment to verify it. In any case, can't guarantee the plugin works on those types of versions.
