### ISSUE TITLE
Horse Bugs

### ISSUE THREAD

**Issue by Cha0sPudd1ng** [ChanceSD/AncientGates#4]
Hi,

Nice Bugfix, THX for you Wonderful work. :)

Even items in the inventory of the mule is also transported.

Only a small display bug exists:

http://img5.fotos-hochladen.net/uploads/muhledisplayerrmdjo1zat5y.png

And I get the following error when i enter the Portal with a /summon Horse:

[15:24:45] [Server thread/INFO]: Cha0sPudd1ng issued server command: /summon EntityHorse ~ ~ ~ {Tame:1,Type:2,SaddleItem:{id:saddle,Count:1}}
[15:24:45] [Server thread/INFO]: [Cha0sPudd1ng: Object successfully summoned]
[15:24:54] [Server thread/ERROR]: Could not pass event EntityPortalEvent to AncientGates v2.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.Entity.c(Entity.java:1918) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.BlockEnderPortal.a(BlockEnderPortal.java:45) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.Entity.checkBlockCollisions(Entity.java:761) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.Entity.move(Entity.java:407) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityLiving.g(EntityLiving.java:1395) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityHorse.g(EntityHorse.java:959) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityLiving.m(EntityLiving.java:1652) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityInsentient.m(EntityInsentient.java:338) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityAgeable.m(EntityAgeable.java:139) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityAnimal.m(EntityAnimal.java:23) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityHorse.m(EntityHorse.java:728) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityLiving.t_(EntityLiving.java:1487) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityInsentient.t_(EntityInsentient.java:193) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.EntityHorse.t_(EntityHorse.java:755) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
Caused by: java.lang.NullPointerException
    at org.mcteam.ancientgates.util.EntityUtil.getEntityTypeData(EntityUtil.java:134) ~[?:?]
    at org.mcteam.ancientgates.sockets.types.Packet.<init>(Packet.java:44) ~[?:?]
    at org.mcteam.ancientgates.util.TeleportUtil.teleportEntity(TeleportUtil.java:217) ~[?:?]
    at org.mcteam.ancientgates.listeners.PluginEntityListener.onEntityPortal(PluginEntityListener.java:63) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8.jar:git-Spigot-0359393-9cd1111]
    ... 26 more

**Comment by ChanceSD** [comment]
This happens when you spawn a tamed horse but with no owner so it's not something i see happening often. I fixed it anyway though, just in case

**Comment by Cha0sPudd1ng** [comment]
THX.

Works fine with the simmoned Horses. ;-)

But the display bug is extant.

**Comment by ChanceSD** [comment]
I know but it's not a big deal, it's just that leather goes into that slot for some reason.
